/**
 * @File Input.hpp
 * @Author dfnzhc (https://github.com/dfnzhc)
 * @Date 2025/8/2
 * @Brief This file is part of Xihe.
 */

#pragma once

#include "Core/Base/Defines.hpp"

namespace xihe {
// clang-format off
enum class KeyCode : u32
{
    Space        = ' ',
    Apostrophe   = '\'',
    Comma        = ',',
    Minus        = '-',
    Period       = '.',
    Slash        = '/',
    Key0         = '0',
    Key1         = '1',
    Key2         = '2',
    Key3         = '3',
    Key4         = '4',
    Key5         = '5',
    Key6         = '6',
    Key7         = '7',
    Key8         = '8',
    Key9         = '9',
    Semicolon    = ';',
    Equal        = '=',
    A            = 'A',
    B            = 'B',
    C            = 'C',
    D            = 'D',
    E            = 'E',
    F            = 'F',
    G            = 'G',
    H            = 'H',
    I            = 'I',
    J            = 'J',
    K            = 'K',
    L            = 'L',
    M            = 'M',
    N            = 'N',
    O            = 'O',
    P            = 'P',
    Q            = 'Q',
    R            = 'R',
    S            = 'S',
    T            = 'T',
    U            = 'U',
    V            = 'V',
    W            = 'W',
    X            = 'X',
    Y            = 'Y',
    Z            = 'Z',
    LeftBracket  = '[',
    Backslash    = '\\',
    RightBracket = ']',
    GraveAccent  = '`',

    Escape         = 256,
    Tab            = 257,
    Enter          = 258,
    Backspace      = 259,
    Insert         = 260,
    Del            = 261,
    Right          = 262,
    Left           = 263,
    Down           = 264,
    Up             = 265,
    PageUp         = 266,
    PageDown       = 267,
    Home           = 268,
    End            = 269,
    CapsLock       = 270,
    ScrollLock     = 271,
    NumLock        = 272,
    PrintScreen    = 273,
    Pause          = 274,
    F1             = 275,
    F2             = 276,
    F3             = 277,
    F4             = 278,
    F5             = 279,
    F6             = 280,
    F7             = 281,
    F8             = 282,
    F9             = 283,
    F10            = 284,
    F11            = 285,
    F12            = 286,
    Keypad0        = 287,
    Keypad1        = 288,
    Keypad2        = 289,
    Keypad3        = 290,
    Keypad4        = 291,
    Keypad5        = 292,
    Keypad6        = 293,
    Keypad7        = 294,
    Keypad8        = 295,
    Keypad9        = 296,
    KeypadDel      = 297,
    KeypadDivide   = 298,
    KeypadMultiply = 299,
    KeypadSubtract = 300,
    KeypadAdd      = 301,
    KeypadEnter    = 302,
    KeypadEqual    = 303,
    LeftShift      = 304,
    LeftControl    = 305,
    LeftAlt        = 306,
    LeftSuper      = 307,
    RightShift     = 308,
    RightControl   = 309,
    RightAlt       = 310,
    RightSuper     = 311,
    Menu           = 312,
    Unknown        = 313
};
// clang-format on

enum class MouseButton : u8
{
    Left = 0,
    Right,
    Middle,
    X1,
    X2
};
} // namespace xihe
